version: "3.8"

services:
  webgame-mongodb:
    image: mongo
    container_name: webgame-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongo-db:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
