version: '3'
services:
  webgame-mysql:
    container_name: webgame-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webgame
      #      MYSQL_USER: sandbox_user
      #      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3310:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - webgame
  webgame-mongodb:
    container_name: webgame-mongodb
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root-webgame'
    volumes:
      - './docker/mongodb:/data/db'
    networks:
      - webgame
  webgame-redis:
    container_name: webgame-redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - './docker/redis:/data'
    networks:
      - webgame
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

networks:
  webgame:
    driver: bridge
volumes:
  webgamemysql:
    driver: local
  webgameredis:
    driver: local
  webgamemongo:
    driver: local

