# Find a player by ID
GET http://localhost:8090/players/6
Accept: application/json

###
# @name DeleteAllPlayers
DELETE http://localhost:8090/players
Content-Type: application/json
### Create a new player
# @name CreatePlayer
POST http://localhost:8090/players
Content-Type: application/json

{
  "username": "Brotzka",
  "email": "fabian.hagen@faaren.com",
  "password": "Passwort",
  "name": "Dingens"
}
###
# @name CreatePlayer
PATCH http://localhost:8090/players/5
Content-Type: application/json

{
  "password": "Passwort"
}
###

